### ISSUE TITLE
pressFlasks

### ISSUE THREAD

**Issue by GrandBonobo** [lmcghee/PoE-Auto-Flasks#1]
Hey, thanks for this!
I'm having issues with running it. When I try to, I get error on line 216:
Line Text: pressFlasks
Error: this line does not contain a recognized action.
Any advice on how to make it work? Thanks!

**Comment by lmcghee** [comment]
@GrandBonobo I'm not able to recreate this from a fresh clone of the repo.
Do you know what version of ahk you are using? I am on 1.1.32.0 and not experiencing any issues.

**Comment by GrandBonobo** [comment]
Thank you for the reply!
I downloaded the files instead of copying the code onto a notepad, and it works now! 
Once again thank you for this! Makes the game way more fun! :)
