### ISSUE TITLE
Hotkeys ?

### ISSUE THREAD

**Issue by sdkyron** [lmcghee/PoE-Auto-Flasks#2]
I guess this assumes that people use default bindings, where can i change that in the script, my flasks are on 7-8-9-0-)

**Comment by lmcghee** [comment]
Hey there! You can edit the values for "keys" in the .ahk file on lines 103-107
Where it says keys:[1] change it to keys:[7] assuming you want to use "7" 
For the parentheses it might work out of the box, but you might need to google ahk special character codes. Not 100% sure.
Considering building this into the ui in a future version. Will @ you if I do.
